name: bmc_audio_example
description: "Demonstrates how to use the bmc_audio plugin."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  bmc_audio:
    path: ../
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.40
  path_provider: ^2.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
