name: bmc_audio
description: "BMC Audio - Capture and decrypt audio from BMC USB Audio (UAC2.0) device with XOR-based encryption."
version: 0.1.0
homepage: https://github.com/bmctechvn/bmc_audio

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  flutter_recorder: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bmc.audio.bmc_audio
        pluginClass: BmcAudioPlugin
      ios:
        pluginClass: BmcAudioPlugin
      linux:
        pluginClass: BmcAudioPlugin
      macos:
        pluginClass: BmcAudioPlugin
      windows:
        pluginClass: BmcAudioPluginCApi
      web:
        pluginClass: BmcAudioWeb
        fileName: bmc_audio_web.dart
